spring:
  application:
    name: eureka
server:
  port: 7903
eureka:
  instance:
    hostname: eureka-7903
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://user:root@eureka-7903:7903/eureka/
